### PR TITLE
Added link to faucet on Battery Station page

### PR DESCRIPTION
**Pull request by jboetticher**
As requested in this parity PR, I've added a link to the discord faucet on the battery station page.

https://github.com/paritytech/contracts-ui/pull/519

### CODE REVIEW

**Review by saboonikhil — CHANGES_REQUESTED** [review]
I'm afraid Discord invite links might expire or reset. How about using redirection link to the channel - https://discord.com/channels/737780518313000960/895033113535725648 ?

My guess is that it would automatically ask new user to join the server.

**Comment by jboetticher** [comment]
It unfortunately does not link to the server if you aren't already a part
of it, at least on mobile.

**Review by saboonikhil — APPROVED** [review]

**Review by saboonikhil — CHANGES_REQUESTED** [review]
Thanks! Do you mind running the script `fmt` for clearance on code formatting?

**Comment by jboetticher** [comment]
Ran the prettier extension @saboonikhil 

BTW, Zeitgeist Battery Station was merged into Contract UI's main:
https://github.com/paritytech/contracts-ui/pull/519#event-10969554531

**Review by saboonikhil — APPROVED** [review]

**Pull request merged**
